name: fluentd-elasticsearch
version: 2.0.7
appVersion: 2.3.2
description: DEPRECATED! - A Fluentd Helm chart for gny project
keywords:
- fluentd
- elasticsearch
- multiline
- detect-exceptions
- logging
deprecated: true
