---
apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-main
  namespace: {{ .Values.namespace }}
  labels:
    addonmanager.kubernetes.io/mode: Reconcile
data:
  fluent.conf: |-
    # This is the root config file, which only includes components of the actual configuration

    # Do not collect fluentd's own logs to avoid infinite loops.
    <label @FLUENT_LOG>
      <match fluent.*>
        # @type null
        @type stdout
      </match>
    </label>
    @include fluentd-gny-conf.d/*
    @include fluentd-ms-conf.d/*
    @include fluentd-midas-conf.d/*
    @include config.d/*.conf
    @include fluentd-es-conf.d/*
