---
kind: ConfigMap
apiVersion: v1
metadata:
  name: fluentd-es-config
  namespace: {{ .Values.namespace }}
  labels:
    addonmanager.kubernetes.io/mode: Reconcile
data:
  system.conf: |-
    <system>
      root_dir /tmp/fluentd-buffers/
    </system>

  containers.input.conf: |-
    <source>
      @id fluentd-containers.log
      @type tail
      path "/var/log/containers/*.log"
      pos_file /var/log/es-containers.log.pos
      tag raw.kubernetes.*
      read_from_head true
      refresh_interval 10s
      <parse>
        @type multi_format
        <pattern>
          format json
          time_key time
          time_format %Y-%m-%dT%H:%M:%S.%NZ
        </pattern>
        <pattern>
          format /^(?<time>.+) (?<stream>stdout|stderr) [^ ]* (?<log>.*)$/
          time_format %Y-%m-%dT%H:%M:%S.%N%:z
        </pattern>
      </parse>
    </source>

    # Detect exceptions in the log output and forward them as one log entry.
    <match raw.kubernetes.**>
      @id raw.kubernetes
      @type detect_exceptions
      remove_tag_prefix raw
      message log
      stream stream
      multiline_flush_interval 5
      max_bytes 500000
      max_lines 1000
    </match>

  forward.input.conf: |-
    # Takes the messages sent over TCP
    <source>
      @type forward
    </source>

  output.conf: |-
    # Enriches records with Kubernetes metadata
    <filter kubernetes.**>
      @type kubernetes_metadata
    </filter>

    # Concatenate multi-line logs
    <filter **>
      @type concat
      key log
      multiline_start_regexp /^(\d{4}-\d{1,2}-\d{1,2})/
      separator ""
      timeout_label @processdata
    </filter>

    <label @processdata>
      <match **>
        @type stdout
      </match>
    </label>
