apiVersion: v1
namespace: logging
image: image_name
host: serverIP

project:
  name: ms

serviceNames:
  - ms-aadhaar-service                                             
  - ms-video-kyc-service
  
ConfigMap:
  name: fluentd-ms-config
  host: server_ip
  type_name: fluentd
  include_tag_key: true
  include_timestamp: true
  time_key_exclude_timestamp: false
  port: 9200
  scheme: http
  ssl_version: TLSv1_2
  ssl_verify: false
  user: fluentd
  password: fluentd
  logstash_format: false
  reconnect_on_error: true
  reload_on_failure: false
  reload_connections: false
  slow_flush_log_threshold: 25.0
  total_limit_size: 1024MB
  flush_mode: interval
  retry_type: exponential_backoff
  flush_thread_count: 20
  flush_interval: 5s
  retry_timeout: 1m
  retry_max_interval: 30
  chunk_limit_size: 10M
  queue_limit_length: 8
  overflow_action: drop_oldest_chunk
  timekey: 0.1h

service:
  name: fluentd
  role: fluentd-read

volumes:
  name1: varlog
  mountPath1: /var/log
  name2: varlibdockercontainers
  mountPath2: /var/lib/docker/containers
  name3: fluentd-main
  mountPath3: /etc/fluent
  name4: fluentd-config
  mountPath4: /etc/fluent/config.d
  name5: fluentd-ms-config
  mountPath5: /etc/fluent/fluentd-ms-conf.d
  name6: fluentd-es-config
